### ISSUE TITLE
Creating a task from a task

### ISSUE THREAD

**Issue by anoteboom** [doitintl/Cloud-Tasks-In-Process-Emulator#1]
I really like the idea of this.  But when i added this emulator to my code, I have this issue.

While processing a task, the lock  is held. While this task is running, I cannot add other tasks, blocking the flow.

Can you do this locking in another way, so that i can create tasks, from within a task?

**Comment by JoshuaFox** [comment]
Fixed in `master`. As a test, the sample app queues a task from inside a handler.
